default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] || ENV['POSTGRES_PORT'] || 5432 %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'postgres' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("POSTGRES_DB") { "sports_book_development" } %>
  reaping_frequency: 10
  prepared_statements: false

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'sports_book_dev' %>

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'sports_book_test' %>

production:
  <<: *default
  pool: 25
  reaping_frequency: 10
